name: Codecov

on:
  push:
    branches:
      - develop  
  pull_request:
    branches:
      - develop  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up JDK 19
      uses: actions/setup-java@v2
      with:
        java-version: 19
        distribution: 'adopt'

    - name: Build and test with Maven
      run: mvn test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }} 
        files: ./target/site/jacoco/jacoco.xml
        flags: unittests
        name: codecov-upload
